[package]
name = "miraland-sdk-macro"
version = "1.14.17"
description = "Miraland SDK Macro"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-sdk-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true
name = "solana_sdk_macro"

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.7"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
