[package]
name = "miraland-local-cluster"
description = "Blockchain for community beyond the horizon"
documentation = "https://docs.rs/miraland-local-cluster"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
miraland-accounts-db = { workspace = true }
miraland-client = { workspace = true }
miraland-config-program = { workspace = true }
miraland-core = { workspace = true }
miraland-entry = { workspace = true }
miraland-gossip = { workspace = true }
miraland-ledger = { workspace = true }
miraland-logger = { workspace = true }
miraland-pubsub-client = { workspace = true }
miraland-rpc-client = { workspace = true }
miraland-rpc-client-api = { workspace = true }
miraland-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-stake-program = { workspace = true }
miraland-streamer = { workspace = true }
miraland-thin-client = { workspace = true }
miraland-tpu-client = { workspace = true }
miraland-turbine = { workspace = true }
miraland-vote = { workspace = true }
miraland-vote-program = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
trees = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
miraland-download-utils = { workspace = true }
miraland-ledger = { workspace = true, features = ["dev-context-only-utils"] }
serial_test = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
