[package]
name = "miraland-sbf-rust-dep-crate"
documentation = "https://docs.rs/miraland-sbf-rust-dep-crate"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
byteorder = { workspace = true }
# list of crates which must be buildable for bpf programs
miraland-program = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
