[package]
name = "miraland-geyser-plugin-manager"
description = "The Miraland Geyser plugin manager."
documentation = "https://docs.rs/miraland-geyser-plugin-manager"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
json5 = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-server-utils = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
miraland-accounts-db = { workspace = true }
miraland-entry = { workspace = true }
miraland-geyser-plugin-interface = { workspace = true }
miraland-ledger = { workspace = true }
miraland-measure = { workspace = true }
miraland-metrics = { workspace = true }
miraland-rpc = { workspace = true }
miraland-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-transaction-status = { workspace = true }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
