[package]
name = "miraland-merkle-tree"
version = "1.14.17-rc3"
description = "Miraland Merkle Tree"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-merkle-tree"
edition = "2021"

[dependencies]
fast-math = "0.1"
miraland-program = { path = "../sdk/program", version = "=1.14.17-rc3" }

# This can go once the BPF toolchain target Rust 1.42.0+
[target.bpfel-unknown-unknown.dependencies]
matches = "0.1.9"

[dev-dependencies]
hex = "0.4.3"

[lib]
crate-type = ["lib"]
name = "solana_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
