[package]
name = "miraland-sbf-rust-secp256k1-recover"
documentation = "https://docs.rs/miraland-sbf-rust-secp256k1-recover"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
libsecp256k1 = { workspace = true }
miraland-program = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
