[package]
name = "miraland-stake-accounts"
description = "Blockchain for community beyond the horizon"
documentation = "https://docs.rs/miraland-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
miraland-clap-utils = { workspace = true }
miraland-cli-config = { workspace = true }
miraland-remote-wallet = { workspace = true, features = ["default"] }
miraland-rpc-client = { workspace = true, features = ["default"] }
miraland-rpc-client-api = { workspace = true }
miraland-sdk = { workspace = true }
miraland-stake-program = { workspace = true }
miraland-version = { workspace = true }

[dev-dependencies]
miraland-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
