[package]
name = "miraland-watchtower"
description = "Blockchain for community beyond the horizon"
documentation = "https://docs.rs/miraland-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
miraland-clap-utils = { workspace = true }
miraland-cli-config = { workspace = true }
miraland-cli-output = { workspace = true }
miraland-logger = { workspace = true }
miraland-metrics = { workspace = true }
miraland-notifier = { workspace = true }
miraland-rpc-client = { workspace = true }
miraland-rpc-client-api = { workspace = true }
miraland-sdk = { workspace = true }
miraland-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
