[package]
name = "miraland-test-validator"
description = "Blockchain for community beyond the horizon"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
miraland-accounts-db = { workspace = true }
miraland-cli-output = { workspace = true }
miraland-client = { workspace = true }
miraland-core = { workspace = true }
miraland-geyser-plugin-manager = { workspace = true }
miraland-gossip = { workspace = true }
miraland-ledger = { workspace = true }
miraland-logger = { workspace = true }
miraland-net-utils = { workspace = true }
miraland-program-runtime = { workspace = true }
miraland-program-test = { workspace = true }
miraland-rpc = { workspace = true }
miraland-rpc-client = { workspace = true }
miraland-runtime = { workspace = true }
miraland-sdk = { workspace = true }
miraland-streamer = { workspace = true }
miraland-tpu-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
