[package]
name = "miraland-storage-bigtable"
version = "1.14.17-rc7"
description = "Miraland Storage BigTable"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Maintainers <maintainers@solana.com>"
]
repository = "https://github.com/miraland-labs/miraland"
license = "Apache-2.0"
homepage = "https://miraland.top/"
documentation = "https://docs.rs/miraland-storage-bigtable"
edition = "2021"

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
bincode = "1.3.3"
bytes = "1.0"
bzip2 = "0.4.4"
enum-iterator = "0.8.1"
flate2 = "1.0.24"
futures = "0.3.21"
goauth = "0.13.0"
http = "0.2.8"
hyper = "0.14.20"
hyper-proxy = "0.9.1"
log = "0.4.17"
miraland-metrics = { path = "../metrics", version = "=1.14.17-rc7" }
miraland-sdk = { path = "../sdk", version = "=1.14.17-rc7" }
miraland-storage-proto = { path = "../storage-proto", version = "=1.14.17-rc7" }
miraland-transaction-status = { path = "../transaction-status", version = "=1.14.17-rc7" }
openssl-src = "=111.25.0+1.1.1t"
prost = "0.11.0"
prost-types = "0.11.0"
serde = "1.0.138"
serde_derive = "1.0.103"
smpl_jwt = "0.7.1"
thiserror = "1.0"
time = "=0.3.9"
tokio = "1"
tonic = { version = "=0.8.0", features = ["tls", "transport"] }
# axum = "=0.6.18"
zstd = "0.11.2"

# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
# statically...
[target."cfg(not(windows))".dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# ...except on Windows to avoid having to deal with getting CI past a build-time
# Perl dependency
[target."cfg(windows)".dependencies]
openssl = { version = "0.10", features = [] }

[lib]
crate-type = ["lib"]
name = "solana_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
