[package]
name = "solana-measure"
description = "Blockchain for community beyond the horizon"
version = "1.14.17"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-measure"
readme = "../README.md"
repository = "https://github.com/miraland-labs/miraland"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.17"
solana-sdk = { path = "../sdk", version = "=1.14.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
