[package]
name = "miraland-rpc-client-nonce-utils"
description = "Miraland RPC Client Nonce Utilities"
documentation = "https://docs.rs/miraland-rpc-client-nonce-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = "2.33.0"
miraland-clap-utils = { workspace = true }
miraland-rpc-client = { workspace = true }
miraland-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
miraland-account-decoder = { workspace = true }
miraland-rpc-client-api = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[lib]
crate-type = ["lib"]
name = "miraland_rpc_client_nonce_utils"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
