[package]
name = "miraland-sbf-rust-rand"
documentation = "https://docs.rs/miraland-sbf-rust-rand"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
getrandom = { workspace = true, features = ["custom"] }
rand = { workspace = true }
miraland-program = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
