[package]
name = "miraland-sbf-rust-custom-heap"
documentation = "https://docs.rs/miraland-sbf-rust-custom-heap"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
miraland-program = { workspace = true }

[features]
default = ["custom-heap"]
custom-heap = []

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
